---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^\.github/workflows/.*\.yml$
      - id: check-json
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: ^\.env*
        args: ["--unique"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: '^\.github/workflows/.*\.yml$'
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]
  - repo: https://github.com/PyCQA/isort.git
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
default_language_version:
  python: python3.12
